infer:
  # pretrained adapter path
  adapter_path: "pretrained_models/0280000.pt"
  sd_path: "pretrained_models/v2-1_512-ema-pruned.ckpt"
  controlnet_path: "pretrained_models/v1_face.pth"
  swinir_path: "pretrained_models/face_swinir_v1.ckpt"
