#打印sd v2.1 unet中所有参数名及其shape

import torch

# 替换为你的 .ckpt 文件路径
ckpt_path = "/DiffBIR/weights/v2-1_512-ema-pruned.ckpt"

# 加载整个 checkpoint
checkpoint = torch.load(ckpt_path, map_location="cpu")

# 预训练模型中unet部分的key前缀为 "model.diffusion_model"
unet_state_dict = {
    k: v for k, v in checkpoint["state_dict"].items()
    if k.startswith("model.diffusion_model")
}

# 打印UNet中所有参数名及其shape
for name, param in unet_state_dict.items():
    print(f"{name}: {param.shape}")



"""
model.diffusion_model.time_embed.0.weight: torch.Size([1280, 320])
model.diffusion_model.time_embed.0.bias: torch.Size([1280])
model.diffusion_model.time_embed.2.weight: torch.Size([1280, 1280])
model.diffusion_model.time_embed.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.0.0.weight: torch.Size([320, 4, 3, 3])
model.diffusion_model.input_blocks.0.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.0.in_layers.0.weight: torch.Size([320])
model.diffusion_model.input_blocks.1.0.in_layers.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.0.in_layers.2.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.input_blocks.1.0.in_layers.2.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.0.emb_layers.1.weight: torch.Size([320, 1280])
model.diffusion_model.input_blocks.1.0.emb_layers.1.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.0.out_layers.0.weight: torch.Size([320])
model.diffusion_model.input_blocks.1.0.out_layers.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.0.out_layers.3.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.input_blocks.1.0.out_layers.3.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.norm.weight: torch.Size([320])
model.diffusion_model.input_blocks.1.1.norm.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.proj_in.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.proj_in.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([2560, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([2560])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.weight: torch.Size([320, 1280])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.ff.net.2.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([320, 1024])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([320, 1024])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.weight: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm1.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.weight: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm2.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.weight: torch.Size([320])
model.diffusion_model.input_blocks.1.1.transformer_blocks.0.norm3.bias: torch.Size([320])
model.diffusion_model.input_blocks.1.1.proj_out.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.1.1.proj_out.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.0.in_layers.0.weight: torch.Size([320])
model.diffusion_model.input_blocks.2.0.in_layers.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.0.in_layers.2.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.input_blocks.2.0.in_layers.2.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.0.emb_layers.1.weight: torch.Size([320, 1280])
model.diffusion_model.input_blocks.2.0.emb_layers.1.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.0.out_layers.0.weight: torch.Size([320])
model.diffusion_model.input_blocks.2.0.out_layers.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.0.out_layers.3.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.input_blocks.2.0.out_layers.3.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.norm.weight: torch.Size([320])
model.diffusion_model.input_blocks.2.1.norm.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.proj_in.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.proj_in.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([2560, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([2560])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.weight: torch.Size([320, 1280])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.ff.net.2.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([320, 1024])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([320, 1024])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1.weight: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm1.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2.weight: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm2.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3.weight: torch.Size([320])
model.diffusion_model.input_blocks.2.1.transformer_blocks.0.norm3.bias: torch.Size([320])
model.diffusion_model.input_blocks.2.1.proj_out.weight: torch.Size([320, 320])
model.diffusion_model.input_blocks.2.1.proj_out.bias: torch.Size([320])
model.diffusion_model.input_blocks.3.0.op.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.input_blocks.3.0.op.bias: torch.Size([320])
model.diffusion_model.input_blocks.4.0.in_layers.0.weight: torch.Size([320])
model.diffusion_model.input_blocks.4.0.in_layers.0.bias: torch.Size([320])
model.diffusion_model.input_blocks.4.0.in_layers.2.weight: torch.Size([640, 320, 3, 3])
model.diffusion_model.input_blocks.4.0.in_layers.2.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.0.emb_layers.1.weight: torch.Size([640, 1280])
model.diffusion_model.input_blocks.4.0.emb_layers.1.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.0.out_layers.0.weight: torch.Size([640])
model.diffusion_model.input_blocks.4.0.out_layers.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.0.out_layers.3.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.input_blocks.4.0.out_layers.3.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.0.skip_connection.weight: torch.Size([640, 320, 1, 1])
model.diffusion_model.input_blocks.4.0.skip_connection.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.norm.weight: torch.Size([640])
model.diffusion_model.input_blocks.4.1.norm.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.proj_in.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.proj_in.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([5120, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([5120])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2.weight: torch.Size([640, 2560])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.ff.net.2.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([640, 1024])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([640, 1024])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1.weight: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm1.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2.weight: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm2.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3.weight: torch.Size([640])
model.diffusion_model.input_blocks.4.1.transformer_blocks.0.norm3.bias: torch.Size([640])
model.diffusion_model.input_blocks.4.1.proj_out.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.4.1.proj_out.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.0.in_layers.0.weight: torch.Size([640])
model.diffusion_model.input_blocks.5.0.in_layers.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.0.in_layers.2.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.input_blocks.5.0.in_layers.2.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.0.emb_layers.1.weight: torch.Size([640, 1280])
model.diffusion_model.input_blocks.5.0.emb_layers.1.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.0.out_layers.0.weight: torch.Size([640])
model.diffusion_model.input_blocks.5.0.out_layers.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.0.out_layers.3.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.input_blocks.5.0.out_layers.3.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.norm.weight: torch.Size([640])
model.diffusion_model.input_blocks.5.1.norm.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.proj_in.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.proj_in.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([5120, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([5120])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2.weight: torch.Size([640, 2560])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.ff.net.2.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([640, 1024])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([640, 1024])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1.weight: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm1.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2.weight: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm2.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3.weight: torch.Size([640])
model.diffusion_model.input_blocks.5.1.transformer_blocks.0.norm3.bias: torch.Size([640])
model.diffusion_model.input_blocks.5.1.proj_out.weight: torch.Size([640, 640])
model.diffusion_model.input_blocks.5.1.proj_out.bias: torch.Size([640])
model.diffusion_model.input_blocks.6.0.op.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.input_blocks.6.0.op.bias: torch.Size([640])
model.diffusion_model.input_blocks.7.0.in_layers.0.weight: torch.Size([640])
model.diffusion_model.input_blocks.7.0.in_layers.0.bias: torch.Size([640])
model.diffusion_model.input_blocks.7.0.in_layers.2.weight: torch.Size([1280, 640, 3, 3])
model.diffusion_model.input_blocks.7.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.7.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.7.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.0.skip_connection.weight: torch.Size([1280, 640, 1, 1])
model.diffusion_model.input_blocks.7.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.norm.weight: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.norm.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.proj_in.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.proj_in.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([10240, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([10240])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2.weight: torch.Size([1280, 5120])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.ff.net.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([1280, 1024])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([1280, 1024])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1.weight: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm1.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2.weight: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3.weight: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.transformer_blocks.0.norm3.bias: torch.Size([1280])
model.diffusion_model.input_blocks.7.1.proj_out.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.7.1.proj_out.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.in_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.in_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.in_layers.2.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.8.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.8.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.norm.weight: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.norm.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.proj_in.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.proj_in.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([10240, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([10240])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2.weight: torch.Size([1280, 5120])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.ff.net.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([1280, 1024])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([1280, 1024])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1.weight: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm1.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2.weight: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3.weight: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.transformer_blocks.0.norm3.bias: torch.Size([1280])
model.diffusion_model.input_blocks.8.1.proj_out.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.8.1.proj_out.bias: torch.Size([1280])
model.diffusion_model.input_blocks.9.0.op.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.9.0.op.bias: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.in_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.in_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.in_layers.2.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.10.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.10.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.10.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.10.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.in_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.in_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.in_layers.2.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.11.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.input_blocks.11.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.input_blocks.11.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.input_blocks.11.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.middle_block.0.in_layers.0.weight: torch.Size([1280])
model.diffusion_model.middle_block.0.in_layers.0.bias: torch.Size([1280])
model.diffusion_model.middle_block.0.in_layers.2.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.middle_block.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.middle_block.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.middle_block.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.middle_block.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.middle_block.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.middle_block.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.norm.weight: torch.Size([1280])
model.diffusion_model.middle_block.1.norm.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.proj_in.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.proj_in.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([10240, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([10240])
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.weight: torch.Size([1280, 5120])
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([1280, 1024])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([1280, 1024])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.weight: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.weight: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.weight: torch.Size([1280])
model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.bias: torch.Size([1280])
model.diffusion_model.middle_block.1.proj_out.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.1.proj_out.bias: torch.Size([1280])
model.diffusion_model.middle_block.2.in_layers.0.weight: torch.Size([1280])
model.diffusion_model.middle_block.2.in_layers.0.bias: torch.Size([1280])
model.diffusion_model.middle_block.2.in_layers.2.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.middle_block.2.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.middle_block.2.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.middle_block.2.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.middle_block.2.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.middle_block.2.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.middle_block.2.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.middle_block.2.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.0.0.in_layers.0.weight: torch.Size([2560])
model.diffusion_model.output_blocks.0.0.in_layers.0.bias: torch.Size([2560])
model.diffusion_model.output_blocks.0.0.in_layers.2.weight: torch.Size([1280, 2560, 3, 3])
model.diffusion_model.output_blocks.0.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.0.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.0.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.0.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.0.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.0.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.0.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.0.0.skip_connection.weight: torch.Size([1280, 2560, 1, 1])
model.diffusion_model.output_blocks.0.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.output_blocks.1.0.in_layers.0.weight: torch.Size([2560])
model.diffusion_model.output_blocks.1.0.in_layers.0.bias: torch.Size([2560])
model.diffusion_model.output_blocks.1.0.in_layers.2.weight: torch.Size([1280, 2560, 3, 3])
model.diffusion_model.output_blocks.1.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.1.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.1.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.1.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.1.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.1.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.1.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.1.0.skip_connection.weight: torch.Size([1280, 2560, 1, 1])
model.diffusion_model.output_blocks.1.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.output_blocks.2.0.in_layers.0.weight: torch.Size([2560])
model.diffusion_model.output_blocks.2.0.in_layers.0.bias: torch.Size([2560])
model.diffusion_model.output_blocks.2.0.in_layers.2.weight: torch.Size([1280, 2560, 3, 3])
model.diffusion_model.output_blocks.2.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.2.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.2.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.2.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.2.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.2.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.2.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.2.0.skip_connection.weight: torch.Size([1280, 2560, 1, 1])
model.diffusion_model.output_blocks.2.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.output_blocks.2.1.conv.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.2.1.conv.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.0.in_layers.0.weight: torch.Size([2560])
model.diffusion_model.output_blocks.3.0.in_layers.0.bias: torch.Size([2560])
model.diffusion_model.output_blocks.3.0.in_layers.2.weight: torch.Size([1280, 2560, 3, 3])
model.diffusion_model.output_blocks.3.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.3.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.3.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.0.skip_connection.weight: torch.Size([1280, 2560, 1, 1])
model.diffusion_model.output_blocks.3.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.norm.weight: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.norm.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.proj_in.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.proj_in.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([10240, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([10240])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.weight: torch.Size([1280, 5120])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.ff.net.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([1280, 1024])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([1280, 1024])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.weight: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.weight: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.weight: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.transformer_blocks.0.norm3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.3.1.proj_out.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.3.1.proj_out.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.0.in_layers.0.weight: torch.Size([2560])
model.diffusion_model.output_blocks.4.0.in_layers.0.bias: torch.Size([2560])
model.diffusion_model.output_blocks.4.0.in_layers.2.weight: torch.Size([1280, 2560, 3, 3])
model.diffusion_model.output_blocks.4.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.4.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.4.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.0.skip_connection.weight: torch.Size([1280, 2560, 1, 1])
model.diffusion_model.output_blocks.4.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.norm.weight: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.norm.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.proj_in.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.proj_in.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([10240, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([10240])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.weight: torch.Size([1280, 5120])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.ff.net.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([1280, 1024])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([1280, 1024])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.weight: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.weight: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.weight: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.transformer_blocks.0.norm3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.4.1.proj_out.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.4.1.proj_out.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.0.in_layers.0.weight: torch.Size([1920])
model.diffusion_model.output_blocks.5.0.in_layers.0.bias: torch.Size([1920])
model.diffusion_model.output_blocks.5.0.in_layers.2.weight: torch.Size([1280, 1920, 3, 3])
model.diffusion_model.output_blocks.5.0.in_layers.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.0.emb_layers.1.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.0.emb_layers.1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.0.out_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.5.0.out_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.0.out_layers.3.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.5.0.out_layers.3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.0.skip_connection.weight: torch.Size([1280, 1920, 1, 1])
model.diffusion_model.output_blocks.5.0.skip_connection.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.norm.weight: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.norm.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.proj_in.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.proj_in.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([10240, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([10240])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.weight: torch.Size([1280, 5120])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.ff.net.2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([1280, 1024])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([1280, 1024])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.weight: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm1.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.weight: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm2.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.weight: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.transformer_blocks.0.norm3.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.1.proj_out.weight: torch.Size([1280, 1280])
model.diffusion_model.output_blocks.5.1.proj_out.bias: torch.Size([1280])
model.diffusion_model.output_blocks.5.2.conv.weight: torch.Size([1280, 1280, 3, 3])
model.diffusion_model.output_blocks.5.2.conv.bias: torch.Size([1280])
model.diffusion_model.output_blocks.6.0.in_layers.0.weight: torch.Size([1920])
model.diffusion_model.output_blocks.6.0.in_layers.0.bias: torch.Size([1920])
model.diffusion_model.output_blocks.6.0.in_layers.2.weight: torch.Size([640, 1920, 3, 3])
model.diffusion_model.output_blocks.6.0.in_layers.2.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.0.emb_layers.1.weight: torch.Size([640, 1280])
model.diffusion_model.output_blocks.6.0.emb_layers.1.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.0.out_layers.0.weight: torch.Size([640])
model.diffusion_model.output_blocks.6.0.out_layers.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.0.out_layers.3.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.output_blocks.6.0.out_layers.3.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.0.skip_connection.weight: torch.Size([640, 1920, 1, 1])
model.diffusion_model.output_blocks.6.0.skip_connection.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.norm.weight: torch.Size([640])
model.diffusion_model.output_blocks.6.1.norm.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.proj_in.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.proj_in.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([5120, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([5120])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2.weight: torch.Size([640, 2560])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.ff.net.2.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([640, 1024])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([640, 1024])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1.weight: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm1.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2.weight: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm2.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3.weight: torch.Size([640])
model.diffusion_model.output_blocks.6.1.transformer_blocks.0.norm3.bias: torch.Size([640])
model.diffusion_model.output_blocks.6.1.proj_out.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.6.1.proj_out.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.0.in_layers.0.weight: torch.Size([1280])
model.diffusion_model.output_blocks.7.0.in_layers.0.bias: torch.Size([1280])
model.diffusion_model.output_blocks.7.0.in_layers.2.weight: torch.Size([640, 1280, 3, 3])
model.diffusion_model.output_blocks.7.0.in_layers.2.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.0.emb_layers.1.weight: torch.Size([640, 1280])
model.diffusion_model.output_blocks.7.0.emb_layers.1.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.0.out_layers.0.weight: torch.Size([640])
model.diffusion_model.output_blocks.7.0.out_layers.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.0.out_layers.3.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.output_blocks.7.0.out_layers.3.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.0.skip_connection.weight: torch.Size([640, 1280, 1, 1])
model.diffusion_model.output_blocks.7.0.skip_connection.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.norm.weight: torch.Size([640])
model.diffusion_model.output_blocks.7.1.norm.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.proj_in.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.proj_in.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([5120, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([5120])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2.weight: torch.Size([640, 2560])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.ff.net.2.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([640, 1024])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([640, 1024])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1.weight: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm1.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2.weight: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm2.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3.weight: torch.Size([640])
model.diffusion_model.output_blocks.7.1.transformer_blocks.0.norm3.bias: torch.Size([640])
model.diffusion_model.output_blocks.7.1.proj_out.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.7.1.proj_out.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.0.in_layers.0.weight: torch.Size([960])
model.diffusion_model.output_blocks.8.0.in_layers.0.bias: torch.Size([960])
model.diffusion_model.output_blocks.8.0.in_layers.2.weight: torch.Size([640, 960, 3, 3])
model.diffusion_model.output_blocks.8.0.in_layers.2.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.0.emb_layers.1.weight: torch.Size([640, 1280])
model.diffusion_model.output_blocks.8.0.emb_layers.1.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.0.out_layers.0.weight: torch.Size([640])
model.diffusion_model.output_blocks.8.0.out_layers.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.0.out_layers.3.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.output_blocks.8.0.out_layers.3.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.0.skip_connection.weight: torch.Size([640, 960, 1, 1])
model.diffusion_model.output_blocks.8.0.skip_connection.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.norm.weight: torch.Size([640])
model.diffusion_model.output_blocks.8.1.norm.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.proj_in.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.proj_in.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([5120, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([5120])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2.weight: torch.Size([640, 2560])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.ff.net.2.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([640, 1024])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([640, 1024])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1.weight: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm1.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2.weight: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm2.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3.weight: torch.Size([640])
model.diffusion_model.output_blocks.8.1.transformer_blocks.0.norm3.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.1.proj_out.weight: torch.Size([640, 640])
model.diffusion_model.output_blocks.8.1.proj_out.bias: torch.Size([640])
model.diffusion_model.output_blocks.8.2.conv.weight: torch.Size([640, 640, 3, 3])
model.diffusion_model.output_blocks.8.2.conv.bias: torch.Size([640])
model.diffusion_model.output_blocks.9.0.in_layers.0.weight: torch.Size([960])
model.diffusion_model.output_blocks.9.0.in_layers.0.bias: torch.Size([960])
model.diffusion_model.output_blocks.9.0.in_layers.2.weight: torch.Size([320, 960, 3, 3])
model.diffusion_model.output_blocks.9.0.in_layers.2.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.0.emb_layers.1.weight: torch.Size([320, 1280])
model.diffusion_model.output_blocks.9.0.emb_layers.1.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.0.out_layers.0.weight: torch.Size([320])
model.diffusion_model.output_blocks.9.0.out_layers.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.0.out_layers.3.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.output_blocks.9.0.out_layers.3.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.0.skip_connection.weight: torch.Size([320, 960, 1, 1])
model.diffusion_model.output_blocks.9.0.skip_connection.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.norm.weight: torch.Size([320])
model.diffusion_model.output_blocks.9.1.norm.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.proj_in.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.proj_in.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([2560, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([2560])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2.weight: torch.Size([320, 1280])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.ff.net.2.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([320, 1024])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([320, 1024])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1.weight: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm1.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2.weight: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm2.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.weight: torch.Size([320])
model.diffusion_model.output_blocks.9.1.transformer_blocks.0.norm3.bias: torch.Size([320])
model.diffusion_model.output_blocks.9.1.proj_out.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.9.1.proj_out.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.0.in_layers.0.weight: torch.Size([640])
model.diffusion_model.output_blocks.10.0.in_layers.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.10.0.in_layers.2.weight: torch.Size([320, 640, 3, 3])
model.diffusion_model.output_blocks.10.0.in_layers.2.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.0.emb_layers.1.weight: torch.Size([320, 1280])
model.diffusion_model.output_blocks.10.0.emb_layers.1.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.0.out_layers.0.weight: torch.Size([320])
model.diffusion_model.output_blocks.10.0.out_layers.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.0.out_layers.3.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.output_blocks.10.0.out_layers.3.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.0.skip_connection.weight: torch.Size([320, 640, 1, 1])
model.diffusion_model.output_blocks.10.0.skip_connection.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.norm.weight: torch.Size([320])
model.diffusion_model.output_blocks.10.1.norm.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.proj_in.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.proj_in.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([2560, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([2560])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2.weight: torch.Size([320, 1280])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.ff.net.2.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([320, 1024])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([320, 1024])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1.weight: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm1.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2.weight: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm2.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3.weight: torch.Size([320])
model.diffusion_model.output_blocks.10.1.transformer_blocks.0.norm3.bias: torch.Size([320])
model.diffusion_model.output_blocks.10.1.proj_out.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.10.1.proj_out.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.0.in_layers.0.weight: torch.Size([640])
model.diffusion_model.output_blocks.11.0.in_layers.0.bias: torch.Size([640])
model.diffusion_model.output_blocks.11.0.in_layers.2.weight: torch.Size([320, 640, 3, 3])
model.diffusion_model.output_blocks.11.0.in_layers.2.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.0.emb_layers.1.weight: torch.Size([320, 1280])
model.diffusion_model.output_blocks.11.0.emb_layers.1.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.0.out_layers.0.weight: torch.Size([320])
model.diffusion_model.output_blocks.11.0.out_layers.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.0.out_layers.3.weight: torch.Size([320, 320, 3, 3])
model.diffusion_model.output_blocks.11.0.out_layers.3.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.0.skip_connection.weight: torch.Size([320, 640, 1, 1])
model.diffusion_model.output_blocks.11.0.skip_connection.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.norm.weight: torch.Size([320])
model.diffusion_model.output_blocks.11.1.norm.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.proj_in.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.proj_in.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_q.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_k.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_v.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj.weight: torch.Size([2560, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.0.proj.bias: torch.Size([2560])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2.weight: torch.Size([320, 1280])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.ff.net.2.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_q.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_k.weight: torch.Size([320, 1024])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight: torch.Size([320, 1024])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1.weight: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm1.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2.weight: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm2.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3.weight: torch.Size([320])
model.diffusion_model.output_blocks.11.1.transformer_blocks.0.norm3.bias: torch.Size([320])
model.diffusion_model.output_blocks.11.1.proj_out.weight: torch.Size([320, 320])
model.diffusion_model.output_blocks.11.1.proj_out.bias: torch.Size([320])
model.diffusion_model.out.0.weight: torch.Size([320])
model.diffusion_model.out.0.bias: torch.Size([320])
model.diffusion_model.out.2.weight: torch.Size([4, 320, 3, 3])
model.diffusion_model.out.2.bias: torch.Size([4])
"""
